---
galaxy_info:
  role_name: nginx
  author: dmitry.s
  description: Deploy nginx in Podman as a systemd Quadlet service
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
